SELECT B.ANIMAL_ID, B.NAME 
    FROM ANIMAL_INS AS A RIGHT JOIN ANIMAL_OUTS AS B
    ON A.ANIMAL_ID= B.ANIMAL_ID
    WHERE B.ANIMAL_ID IS NOT NULL
        AND A.ANIMAL_ID IS NULL
    ORDER BY A.ANIMAL_ID