SELECT NAME, DATETIME
    FROM ANIMAL_INS 
        WHERE ANIMAL_ID NOT IN(
        SELECT A.ANIMAL_ID
            FROM ANIMAL_INS AS A JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID=B.ANIMAL_ID
        )
    ORDER BY DATETIME
    LIMIT 3
    