SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
    FROM DEVELOPERS AS A
        JOIN SKILLCODES AS B
        ON B.CODE & A.SKILL_CODE = B.CODE
    WHERE B.CATEGORY = 'Front End'
    GROUP BY A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
    ORDER BY A.ID ASC;
