-- 코드를 작성해주세요
SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
    FROM ITEM_INFO AS A JOIN ITEM_TREE AS B
        ON A.ITEM_ID=B.ITEM_ID
        JOIN ITEM_INFO AS PARENT ON B.PARENT_ITEM_ID = PARENT.ITEM_ID
        WHERE PARENT.RARITY = 'RARE'
        ORDER BY ITEM_ID DESC