SELECT 
    YEAR(A.DIFFERENTIATION_DATE) AS YEAR,                       (MAX(A.SIZE_OF_COLONY) OVER (PARTITION BY YEAR(A.DIFFERENTIATION_DATE)) - A.SIZE_OF_COLONY) AS YEAR_DEV ,
    A.ID
FROM ECOLI_DATA AS A
ORDER BY YEAR(A.DIFFERENTIATION_DATE),  
        YEAR_DEV;                   
