-- 코드를 작성해주세요
SELECT FISH_INFO.ID, FISH_NAME_INFO.FISH_NAME, FISH_INFO.LENGTH
    FROM FISH_INFO JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
        JOIN(
            SELECT FISH_INFO.FISH_TYPE, MAX(FISH_INFO.LENGTH)AS MAX_LENGTH FROM FISH_INFO
                GROUP BY FISH_TYPE
        )AS MAX_FISH ON FISH_INFO.FISH_TYPE=MAX_FISH.FISH_TYPE AND FISH_INFO.LENGTH=MAX_FISH.MAX_LENGTH
    ORDER BY FISH_INFO.ID ASC