SELECT B.SCORE, A.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
    FROM  HR_EMPLOYEES AS A JOIN(
        SELECT EMP_NO, SUM(SCORE)AS SCORE
            FROM HR_GRADE AS B
            WHERE YEAR = 2022
            GROUP BY EMP_NO
    )AS B ON A.EMP_NO=B.EMP_NO
    ORDER BY B.SCORE DESC
    LIMIT 1