SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT AS F1
WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
AND PRICE = (
    SELECT MAX(PRICE)
    FROM FOOD_PRODUCT AS F2
    WHERE F1.CATEGORY = F2.CATEGORY
)
ORDER BY MAX_PRICE DESC;
